create table PERSON (
	id int generated by default as identity primary key,
	name varchar(50) unique not null,
	year date	
);

create table BOOK (
	id int generated by default as identity primary key,
	name varchar(200) not null,
	author varchar(80) not null,
	year date,
	person_id int references person(id) ON DELETE CASCADE	
);